"""changes

Revision ID: 162f5dc39d53
Revises: 07bb96ab40b4
Create Date: 2024-06-29 15:06:14.457998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '162f5dc39d53'
down_revision = '07bb96ab40b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_column('name')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
