"""changes

Revision ID: 1f04f28ed745
Revises: 3210634c4099
Create Date: 2024-07-07 01:08:19.783357

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f04f28ed745'
down_revision = '3210634c4099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=False))
        batch_op.drop_column('descriptions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descriptions', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
