"""changes

Revision ID: 2d256b7f145a
Revises: c177a82bceba
Create Date: 2024-07-03 23:34:43.999009

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d256b7f145a'
down_revision = 'c177a82bceba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('reviews_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'restaurant', ['restaurant_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reviews_ibfk_3', 'users', ['user_id'], ['id'])
        batch_op.drop_column('restaurant_id')

    # ### end Alembic commands ###
