"""changes

Revision ID: 34f33bef0358
Revises: 2055d17b11fe
Create Date: 2024-07-03 22:53:36.287308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34f33bef0358'
down_revision = '2055d17b11fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('reviews_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('reviews_ibfk_2', type_='foreignkey')
        batch_op.drop_column('tick')
        batch_op.drop_column('restaurant_id')
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('restaurant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tick', mysql.VARCHAR(length=100), nullable=True))
        batch_op.create_foreign_key('reviews_ibfk_2', 'restaurant', ['restaurant_id'], ['id'])
        batch_op.create_foreign_key('reviews_ibfk_1', 'orders', ['order_id'], ['id'])

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
