"""changes

Revision ID: 3d11dcf60e91
Revises: 42f70bfcea24
Create Date: 2024-06-29 16:33:28.272853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d11dcf60e91'
down_revision = '42f70bfcea24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('contact', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_column('contact')
        batch_op.drop_column('role')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
