"""changes

Revision ID: 8fca7826e330
Revises: 1f04f28ed745
Create Date: 2024-07-07 23:15:47.655636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8fca7826e330'
down_revision = '1f04f28ed745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', mysql.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
