"""changes

Revision ID: b2cfa8fa4539
Revises: 3047371eaa81
Create Date: 2024-07-06 12:07:12.357815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2cfa8fa4539'
down_revision = '3047371eaa81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.drop_constraint('orders_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('orders_ibfk_1', type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('quantity')
        batch_op.drop_column('restaurant_id')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('Items')
        batch_op.drop_column('order_date')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('transactions_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'order_items', ['orderItem_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transactions_ibfk_1', 'order_item', ['orderItem_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_date', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('Items', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('payment_method', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('restaurant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True))
        batch_op.create_foreign_key('orders_ibfk_1', 'restaurant', ['restaurant_id'], ['id'])
        batch_op.create_foreign_key('orders_ibfk_2', 'users', ['user_id'], ['id'])
        batch_op.alter_column('status',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    op.create_table('order_item',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('item_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('total_amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name='order_item_ibfk_1'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='order_item_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
