"""new changes

Revision ID: c610c06b3fdd
Revises: 0d8bc3f5c90c
Create Date: 2024-06-13 11:53:10.020406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c610c06b3fdd'
down_revision = '0d8bc3f5c90c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tick', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('tick')

    # ### end Alembic commands ###
