"""changes

Revision ID: c6e2abe041c3
Revises: 9ea3c80e01ca
Create Date: 2024-07-16 12:49:12.591816

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6e2abe041c3'
down_revision = '9ea3c80e01ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('total_amount',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('total_amount',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
