name: Build and Push Docker Images

on:
  push:
    branches: [main]

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./My_Project
          file: ./My_Project/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/witu:latest

      - name: Log out of Docker Hub
        run: docker logout

  build-and-push-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./restaurant-website
          file: ./restaurant-website/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/witu:latest

      - name: Log out of Docker Hub
        run: docker logout
